### ISSUE TITLE
A list of components in a slot or prop can't be looped the same way by ui pattern and storybook

### ISSUE THREAD

**Issue by Fred-Boulanger** [iberdinsky-skilld/sdc-addon#48]
There is an issue for props type array to embed components. for example in slider :
[slider.component.yml]
```
props:
  type: object
  properties:
    slides:
          title: Slider Items
          type: array
          examples:
            - ['slide 1', 'slide 2', 'slide 3', 'slide 4']
```
slider.default.story.yml
```
name: Cards
props:
  slides:
    - type: component
      component: 'umami:card'
      story: Preview
    - type: component
      component: 'umami:card'
      story: Preview
    - type: component
      component: 'umami:card'
      story: Preview
```

This does'nt work with ui pattern (issue in library)

In other way, I have try to use a slot to embed multiple components. It's work well with ui pattern but the twig loop doesn't work correctly in storybook :
```
{% for slide in slides %}
  <div class="swiper-slide o-slider__slide">{{ slide }}</div>
{% endfor %}
```
all components of the list are in a single slide
